### ISSUE TITLE
Ablage für Bilddateien

### ISSUE THREAD

**Issue by heyeje** [xHain-hackspace/xHain_Hugo#10]
Wir brauchen einen Ort, an dem wir Beitragsbilder und Thumbnails ablegen können. Entweder direkt im Projekt oder extern.

**Comment by Martin1001** [comment]
Die Bilder können nun unter /static/images/ abgelegt werden. In Post können die Bilder dann mit nur wie folgt eingebunden werden.

thumbnailImage: image/bild.jpg
